config/routes.rb
Rails.application.routes.draw do
  get 'users/profile'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  get '/u/:id', to: 'users#profile', as: "user"

  resources :posts
  get 'about', to: 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/views/layouts/_alerts.html.erb
<% if notice %>
    <p class="notice"><%= notice %></p>
<% end %>

<% if alert %>
    <p class="alert"><%= alert %></p>
<% end %>

app/views/layouts/_navbar.html.erb
<ul class="nav">
  <% if current_user %>
  <p>Welcome <%= current_user.name %></p>
  <% end %>

  <li class="nav-item">
    <%= link_to "Home", root_path, class:"nav-link" %>
  </li>
  <li class="nav-item">
       <%= link_to "About", about_path, class:"nav-link" %>
  </li>
  <li class="nav-item">
       <%= link_to "Blog", posts_path, class:"nav-link" %>
  </li>
  
  <%= render 'user/session_manager' %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogYt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navbar' %>
      <%= render 'layouts/alerts' %>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>